### ISSUE TITLE
minimum-stability error

### ISSUE THREAD

**Issue by igorveremsky** [sadovojav/yii2-gallery-module#6]
![screenshot_293](https://user-images.githubusercontent.com/13087365/40846776-38b125f6-65c3-11e8-9f87-e2552a4dcfc1.png)

**Comment by sadovyiov** [comment]
Try to add or update this fields to package.json

"minimum-stability": "dev",
"prefer-stable": true,

**Comment by igorveremsky** [comment]
@sadovojav maybe there another way to do it because by change minimum-stability all packages will updated

**Comment by sadovyiov** [comment]
"prefer-stable": true - say if package has stable version, it will be install

**Comment by sadovyiov** [comment]
@igorveremsky http://webtips.krajee.com/setting-composer-minimum-stability-application/

**Comment by igorveremsky** [comment]
@sadovojav thanks now it works
